remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: [Luis Tomás' Blog]
description: [Blog about Cloud, Containers, Networking, Open Source, and other related stuff]
show_downloads: ["true"]
